version: '3.3'

services:
  mongodb:
    image: mongo:${MONGO_VERSION}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ${MONGO_VOLUME}:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
