version: '3.3'
services:
  redisdb:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '${DB_PORT}:${DB_PORT}'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
volumes:
  cache:
    driver: local
