version: '3.3'
services:
  redisdb:
    image: redis:${REDIS_VERSION}-alpine
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    command: redis-server --save ${REDIS_SAVE_FREQUENCY} ${REDIS_SAVE_THRESHOLD} --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes: 
      - cache:/data
volumes:
  cache:
    driver: local
