version: '3.3'
services:
  mysqldb:
    image: mysql:${MYSQL_VERSION}
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    expose:
      - ${DB_PORT}
    volumes:
      - ${MYSQL_VOLUME}:/var/lib/mysql
      - ${SQL_FILE_PATH}:/docker-entry-point-initdb.d/${SQL_FILE_NAME}
volumes:
  ${MYSQL_VOLUME}:
